import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
// 部署目标：仓库根即 Obsidian vault 根，插件目录在 .obsidian/plugins/cirast-checkin。
// 如需部署到别的 vault，设置环境变量 DEPLOY_DIR 覆盖（绝对路径）。
const DEPLOY_DIR = process.env.DEPLOY_DIR
  || join(__dirname, "..", ".obsidian", "plugins", "cirast-checkin");
const DEPLOY_FILES = ["main.js", "manifest.json", "styles.css"];

function deploy() {
  if (!existsSync(DEPLOY_DIR)) mkdirSync(DEPLOY_DIR, { recursive: true });
  for (const f of DEPLOY_FILES) {
    const src = join(__dirname, f);
    if (!existsSync(src)) continue;
    copyFileSync(src, join(DEPLOY_DIR, f));
  }
  console.log(`[deploy] 已同步到 ${DEPLOY_DIR}`);
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's repo.
*/`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  deploy();
  process.exit(0);
} else {
  await context.watch();
}
