/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's repo.
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CirastCheckinPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/shareModal.ts
var import_obsidian = require("obsidian");

// node_modules/html-to-image/es/util.js
function resolveUrl(url, baseUrl) {
  if (url.match(/^[a-z]+:\/\//i)) {
    return url;
  }
  if (url.match(/^\/\//)) {
    return window.location.protocol + url;
  }
  if (url.match(/^[a-z]+:/i)) {
    return url;
  }
  const doc = document.implementation.createHTMLDocument();
  const base = doc.createElement("base");
  const a = doc.createElement("a");
  doc.head.appendChild(base);
  doc.body.appendChild(a);
  if (baseUrl) {
    base.href = baseUrl;
  }
  a.href = url;
  return a.href;
}
var uuid = /* @__PURE__ */ (() => {
  let counter = 0;
  const random = () => (
    // eslint-disable-next-line no-bitwise
    `0000${(Math.random() * 36 ** 4 << 0).toString(36)}`.slice(-4)
  );
  return () => {
    counter += 1;
    return `u${random()}${counter}`;
  };
})();
function toArray(arrayLike) {
  const arr = [];
  for (let i = 0, l = arrayLike.length; i < l; i++) {
    arr.push(arrayLike[i]);
  }
  return arr;
}
var styleProps = null;
function getStyleProperties(options = {}) {
  if (styleProps) {
    return styleProps;
  }
  if (options.includeStyleProperties) {
    styleProps = options.includeStyleProperties;
    return styleProps;
  }
  styleProps = toArray(window.getComputedStyle(document.documentElement));
  return styleProps;
}
function px(node, styleProperty) {
  const win = node.ownerDocument.defaultView || window;
  const val = win.getComputedStyle(node).getPropertyValue(styleProperty);
  return val ? parseFloat(val.replace("px", "")) : 0;
}
function getNodeWidth(node) {
  const leftBorder = px(node, "border-left-width");
  const rightBorder = px(node, "border-right-width");
  return node.clientWidth + leftBorder + rightBorder;
}
function getNodeHeight(node) {
  const topBorder = px(node, "border-top-width");
  const bottomBorder = px(node, "border-bottom-width");
  return node.clientHeight + topBorder + bottomBorder;
}
function getImageSize(targetNode, options = {}) {
  const width = options.width || getNodeWidth(targetNode);
  const height = options.height || getNodeHeight(targetNode);
  return { width, height };
}
function getPixelRatio() {
  let ratio;
  let FINAL_PROCESS;
  try {
    FINAL_PROCESS = process;
  } catch (e) {
  }
  const val = FINAL_PROCESS && FINAL_PROCESS.env ? FINAL_PROCESS.env.devicePixelRatio : null;
  if (val) {
    ratio = parseInt(val, 10);
    if (Number.isNaN(ratio)) {
      ratio = 1;
    }
  }
  return ratio || window.devicePixelRatio || 1;
}
var canvasDimensionLimit = 16384;
function checkCanvasDimensions(canvas) {
  if (canvas.width > canvasDimensionLimit || canvas.height > canvasDimensionLimit) {
    if (canvas.width > canvasDimensionLimit && canvas.height > canvasDimensionLimit) {
      if (canvas.width > canvas.height) {
        canvas.height *= canvasDimensionLimit / canvas.width;
        canvas.width = canvasDimensionLimit;
      } else {
        canvas.width *= canvasDimensionLimit / canvas.height;
        canvas.height = canvasDimensionLimit;
      }
    } else if (canvas.width > canvasDimensionLimit) {
      canvas.height *= canvasDimensionLimit / canvas.width;
      canvas.width = canvasDimensionLimit;
    } else {
      canvas.width *= canvasDimensionLimit / canvas.height;
      canvas.height = canvasDimensionLimit;
    }
  }
}
function createImage(url) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      img.decode().then(() => {
        requestAnimationFrame(() => resolve(img));
      });
    };
    img.onerror = reject;
    img.crossOrigin = "anonymous";
    img.decoding = "async";
    img.src = url;
  });
}
async function svgToDataURL(svg) {
  return Promise.resolve().then(() => new XMLSerializer().serializeToString(svg)).then(encodeURIComponent).then((html) => `data:image/svg+xml;charset=utf-8,${html}`);
}
async function nodeToDataURL(node, width, height) {
  const xmlns = "http://www.w3.org/2000/svg";
  const svg = document.createElementNS(xmlns, "svg");
  const foreignObject = document.createElementNS(xmlns, "foreignObject");
  svg.setAttribute("width", `${width}`);
  svg.setAttribute("height", `${height}`);
  svg.setAttribute("viewBox", `0 0 ${width} ${height}`);
  foreignObject.setAttribute("width", "100%");
  foreignObject.setAttribute("height", "100%");
  foreignObject.setAttribute("x", "0");
  foreignObject.setAttribute("y", "0");
  foreignObject.setAttribute("externalResourcesRequired", "true");
  svg.appendChild(foreignObject);
  foreignObject.appendChild(node);
  return svgToDataURL(svg);
}
var isInstanceOfElement = (node, instance) => {
  if (node instanceof instance)
    return true;
  const nodePrototype = Object.getPrototypeOf(node);
  if (nodePrototype === null)
    return false;
  return nodePrototype.constructor.name === instance.name || isInstanceOfElement(nodePrototype, instance);
};

// node_modules/html-to-image/es/clone-pseudos.js
function formatCSSText(style) {
  const content = style.getPropertyValue("content");
  return `${style.cssText} content: '${content.replace(/'|"/g, "")}';`;
}
function formatCSSProperties(style, options) {
  return getStyleProperties(options).map((name) => {
    const value = style.getPropertyValue(name);
    const priority = style.getPropertyPriority(name);
    return `${name}: ${value}${priority ? " !important" : ""};`;
  }).join(" ");
}
function getPseudoElementStyle(className, pseudo, style, options) {
  const selector = `.${className}:${pseudo}`;
  const cssText = style.cssText ? formatCSSText(style) : formatCSSProperties(style, options);
  return document.createTextNode(`${selector}{${cssText}}`);
}
function clonePseudoElement(nativeNode, clonedNode, pseudo, options) {
  const style = window.getComputedStyle(nativeNode, pseudo);
  const content = style.getPropertyValue("content");
  if (content === "" || content === "none") {
    return;
  }
  const className = uuid();
  try {
    clonedNode.className = `${clonedNode.className} ${className}`;
  } catch (err) {
    return;
  }
  const styleElement = document.createElement("style");
  styleElement.appendChild(getPseudoElementStyle(className, pseudo, style, options));
  clonedNode.appendChild(styleElement);
}
function clonePseudoElements(nativeNode, clonedNode, options) {
  clonePseudoElement(nativeNode, clonedNode, ":before", options);
  clonePseudoElement(nativeNode, clonedNode, ":after", options);
}

// node_modules/html-to-image/es/mimes.js
var WOFF = "application/font-woff";
var JPEG = "image/jpeg";
var mimes = {
  woff: WOFF,
  woff2: WOFF,
  ttf: "application/font-truetype",
  eot: "application/vnd.ms-fontobject",
  png: "image/png",
  jpg: JPEG,
  jpeg: JPEG,
  gif: "image/gif",
  tiff: "image/tiff",
  svg: "image/svg+xml",
  webp: "image/webp"
};
function getExtension(url) {
  const match = /\.([^./]*?)$/g.exec(url);
  return match ? match[1] : "";
}
function getMimeType(url) {
  const extension = getExtension(url).toLowerCase();
  return mimes[extension] || "";
}

// node_modules/html-to-image/es/dataurl.js
function getContentFromDataUrl(dataURL) {
  return dataURL.split(/,/)[1];
}
function isDataUrl(url) {
  return url.search(/^(data:)/) !== -1;
}
function makeDataUrl(content, mimeType) {
  return `data:${mimeType};base64,${content}`;
}
async function fetchAsDataURL(url, init, process2) {
  const res = await fetch(url, init);
  if (res.status === 404) {
    throw new Error(`Resource "${res.url}" not found`);
  }
  const blob = await res.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = reject;
    reader.onloadend = () => {
      try {
        resolve(process2({ res, result: reader.result }));
      } catch (error) {
        reject(error);
      }
    };
    reader.readAsDataURL(blob);
  });
}
var cache = {};
function getCacheKey(url, contentType, includeQueryParams) {
  let key = url.replace(/\?.*/, "");
  if (includeQueryParams) {
    key = url;
  }
  if (/ttf|otf|eot|woff2?/i.test(key)) {
    key = key.replace(/.*\//, "");
  }
  return contentType ? `[${contentType}]${key}` : key;
}
async function resourceToDataURL(resourceUrl, contentType, options) {
  const cacheKey = getCacheKey(resourceUrl, contentType, options.includeQueryParams);
  if (cache[cacheKey] != null) {
    return cache[cacheKey];
  }
  if (options.cacheBust) {
    resourceUrl += (/\?/.test(resourceUrl) ? "&" : "?") + (/* @__PURE__ */ new Date()).getTime();
  }
  let dataURL;
  try {
    const content = await fetchAsDataURL(resourceUrl, options.fetchRequestInit, ({ res, result }) => {
      if (!contentType) {
        contentType = res.headers.get("Content-Type") || "";
      }
      return getContentFromDataUrl(result);
    });
    dataURL = makeDataUrl(content, contentType);
  } catch (error) {
    dataURL = options.imagePlaceholder || "";
    let msg = `Failed to fetch resource: ${resourceUrl}`;
    if (error) {
      msg = typeof error === "string" ? error : error.message;
    }
    if (msg) {
      console.warn(msg);
    }
  }
  cache[cacheKey] = dataURL;
  return dataURL;
}

// node_modules/html-to-image/es/clone-node.js
async function cloneCanvasElement(canvas) {
  const dataURL = canvas.toDataURL();
  if (dataURL === "data:,") {
    return canvas.cloneNode(false);
  }
  return createImage(dataURL);
}
async function cloneVideoElement(video, options) {
  if (video.currentSrc) {
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    canvas.width = video.clientWidth;
    canvas.height = video.clientHeight;
    ctx === null || ctx === void 0 ? void 0 : ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
    const dataURL2 = canvas.toDataURL();
    return createImage(dataURL2);
  }
  const poster = video.poster;
  const contentType = getMimeType(poster);
  const dataURL = await resourceToDataURL(poster, contentType, options);
  return createImage(dataURL);
}
async function cloneIFrameElement(iframe, options) {
  var _a;
  try {
    if ((_a = iframe === null || iframe === void 0 ? void 0 : iframe.contentDocument) === null || _a === void 0 ? void 0 : _a.body) {
      return await cloneNode(iframe.contentDocument.body, options, true);
    }
  } catch (_b) {
  }
  return iframe.cloneNode(false);
}
async function cloneSingleNode(node, options) {
  if (isInstanceOfElement(node, HTMLCanvasElement)) {
    return cloneCanvasElement(node);
  }
  if (isInstanceOfElement(node, HTMLVideoElement)) {
    return cloneVideoElement(node, options);
  }
  if (isInstanceOfElement(node, HTMLIFrameElement)) {
    return cloneIFrameElement(node, options);
  }
  return node.cloneNode(isSVGElement(node));
}
var isSlotElement = (node) => node.tagName != null && node.tagName.toUpperCase() === "SLOT";
var isSVGElement = (node) => node.tagName != null && node.tagName.toUpperCase() === "SVG";
async function cloneChildren(nativeNode, clonedNode, options) {
  var _a, _b;
  if (isSVGElement(clonedNode)) {
    return clonedNode;
  }
  let children = [];
  if (isSlotElement(nativeNode) && nativeNode.assignedNodes) {
    children = toArray(nativeNode.assignedNodes());
  } else if (isInstanceOfElement(nativeNode, HTMLIFrameElement) && ((_a = nativeNode.contentDocument) === null || _a === void 0 ? void 0 : _a.body)) {
    children = toArray(nativeNode.contentDocument.body.childNodes);
  } else {
    children = toArray(((_b = nativeNode.shadowRoot) !== null && _b !== void 0 ? _b : nativeNode).childNodes);
  }
  if (children.length === 0 || isInstanceOfElement(nativeNode, HTMLVideoElement)) {
    return clonedNode;
  }
  await children.reduce((deferred, child) => deferred.then(() => cloneNode(child, options)).then((clonedChild) => {
    if (clonedChild) {
      clonedNode.appendChild(clonedChild);
    }
  }), Promise.resolve());
  return clonedNode;
}
function cloneCSSStyle(nativeNode, clonedNode, options) {
  const targetStyle = clonedNode.style;
  if (!targetStyle) {
    return;
  }
  const sourceStyle = window.getComputedStyle(nativeNode);
  if (sourceStyle.cssText) {
    targetStyle.cssText = sourceStyle.cssText;
    targetStyle.transformOrigin = sourceStyle.transformOrigin;
  } else {
    getStyleProperties(options).forEach((name) => {
      let value = sourceStyle.getPropertyValue(name);
      if (name === "font-size" && value.endsWith("px")) {
        const reducedFont = Math.floor(parseFloat(value.substring(0, value.length - 2))) - 0.1;
        value = `${reducedFont}px`;
      }
      if (isInstanceOfElement(nativeNode, HTMLIFrameElement) && name === "display" && value === "inline") {
        value = "block";
      }
      if (name === "d" && clonedNode.getAttribute("d")) {
        value = `path(${clonedNode.getAttribute("d")})`;
      }
      targetStyle.setProperty(name, value, sourceStyle.getPropertyPriority(name));
    });
  }
}
function cloneInputValue(nativeNode, clonedNode) {
  if (isInstanceOfElement(nativeNode, HTMLTextAreaElement)) {
    clonedNode.innerHTML = nativeNode.value;
  }
  if (isInstanceOfElement(nativeNode, HTMLInputElement)) {
    clonedNode.setAttribute("value", nativeNode.value);
  }
}
function cloneSelectValue(nativeNode, clonedNode) {
  if (isInstanceOfElement(nativeNode, HTMLSelectElement)) {
    const clonedSelect = clonedNode;
    const selectedOption = Array.from(clonedSelect.children).find((child) => nativeNode.value === child.getAttribute("value"));
    if (selectedOption) {
      selectedOption.setAttribute("selected", "");
    }
  }
}
function decorate(nativeNode, clonedNode, options) {
  if (isInstanceOfElement(clonedNode, Element)) {
    cloneCSSStyle(nativeNode, clonedNode, options);
    clonePseudoElements(nativeNode, clonedNode, options);
    cloneInputValue(nativeNode, clonedNode);
    cloneSelectValue(nativeNode, clonedNode);
  }
  return clonedNode;
}
async function ensureSVGSymbols(clone, options) {
  const uses = clone.querySelectorAll ? clone.querySelectorAll("use") : [];
  if (uses.length === 0) {
    return clone;
  }
  const processedDefs = {};
  for (let i = 0; i < uses.length; i++) {
    const use = uses[i];
    const id = use.getAttribute("xlink:href");
    if (id) {
      const exist = clone.querySelector(id);
      const definition = document.querySelector(id);
      if (!exist && definition && !processedDefs[id]) {
        processedDefs[id] = await cloneNode(definition, options, true);
      }
    }
  }
  const nodes = Object.values(processedDefs);
  if (nodes.length) {
    const ns = "http://www.w3.org/1999/xhtml";
    const svg = document.createElementNS(ns, "svg");
    svg.setAttribute("xmlns", ns);
    svg.style.position = "absolute";
    svg.style.width = "0";
    svg.style.height = "0";
    svg.style.overflow = "hidden";
    svg.style.display = "none";
    const defs = document.createElementNS(ns, "defs");
    svg.appendChild(defs);
    for (let i = 0; i < nodes.length; i++) {
      defs.appendChild(nodes[i]);
    }
    clone.appendChild(svg);
  }
  return clone;
}
async function cloneNode(node, options, isRoot) {
  if (!isRoot && options.filter && !options.filter(node)) {
    return null;
  }
  return Promise.resolve(node).then((clonedNode) => cloneSingleNode(clonedNode, options)).then((clonedNode) => cloneChildren(node, clonedNode, options)).then((clonedNode) => decorate(node, clonedNode, options)).then((clonedNode) => ensureSVGSymbols(clonedNode, options));
}

// node_modules/html-to-image/es/embed-resources.js
var URL_REGEX = /url\((['"]?)([^'"]+?)\1\)/g;
var URL_WITH_FORMAT_REGEX = /url\([^)]+\)\s*format\((["']?)([^"']+)\1\)/g;
var FONT_SRC_REGEX = /src:\s*(?:url\([^)]+\)\s*format\([^)]+\)[,;]\s*)+/g;
function toRegex(url) {
  const escaped = url.replace(/([.*+?^${}()|\[\]\/\\])/g, "\\$1");
  return new RegExp(`(url\\(['"]?)(${escaped})(['"]?\\))`, "g");
}
function parseURLs(cssText) {
  const urls = [];
  cssText.replace(URL_REGEX, (raw, quotation, url) => {
    urls.push(url);
    return raw;
  });
  return urls.filter((url) => !isDataUrl(url));
}
async function embed(cssText, resourceURL, baseURL, options, getContentFromUrl) {
  try {
    const resolvedURL = baseURL ? resolveUrl(resourceURL, baseURL) : resourceURL;
    const contentType = getMimeType(resourceURL);
    let dataURL;
    if (getContentFromUrl) {
      const content = await getContentFromUrl(resolvedURL);
      dataURL = makeDataUrl(content, contentType);
    } else {
      dataURL = await resourceToDataURL(resolvedURL, contentType, options);
    }
    return cssText.replace(toRegex(resourceURL), `$1${dataURL}$3`);
  } catch (error) {
  }
  return cssText;
}
function filterPreferredFontFormat(str, { preferredFontFormat }) {
  return !preferredFontFormat ? str : str.replace(FONT_SRC_REGEX, (match) => {
    while (true) {
      const [src, , format] = URL_WITH_FORMAT_REGEX.exec(match) || [];
      if (!format) {
        return "";
      }
      if (format === preferredFontFormat) {
        return `src: ${src};`;
      }
    }
  });
}
function shouldEmbed(url) {
  return url.search(URL_REGEX) !== -1;
}
async function embedResources(cssText, baseUrl, options) {
  if (!shouldEmbed(cssText)) {
    return cssText;
  }
  const filteredCSSText = filterPreferredFontFormat(cssText, options);
  const urls = parseURLs(filteredCSSText);
  return urls.reduce((deferred, url) => deferred.then((css) => embed(css, url, baseUrl, options)), Promise.resolve(filteredCSSText));
}

// node_modules/html-to-image/es/embed-images.js
async function embedProp(propName, node, options) {
  var _a;
  const propValue = (_a = node.style) === null || _a === void 0 ? void 0 : _a.getPropertyValue(propName);
  if (propValue) {
    const cssString = await embedResources(propValue, null, options);
    node.style.setProperty(propName, cssString, node.style.getPropertyPriority(propName));
    return true;
  }
  return false;
}
async function embedBackground(clonedNode, options) {
  ;
  await embedProp("background", clonedNode, options) || await embedProp("background-image", clonedNode, options);
  await embedProp("mask", clonedNode, options) || await embedProp("-webkit-mask", clonedNode, options) || await embedProp("mask-image", clonedNode, options) || await embedProp("-webkit-mask-image", clonedNode, options);
}
async function embedImageNode(clonedNode, options) {
  const isImageElement = isInstanceOfElement(clonedNode, HTMLImageElement);
  if (!(isImageElement && !isDataUrl(clonedNode.src)) && !(isInstanceOfElement(clonedNode, SVGImageElement) && !isDataUrl(clonedNode.href.baseVal))) {
    return;
  }
  const url = isImageElement ? clonedNode.src : clonedNode.href.baseVal;
  const dataURL = await resourceToDataURL(url, getMimeType(url), options);
  await new Promise((resolve, reject) => {
    clonedNode.onload = resolve;
    clonedNode.onerror = options.onImageErrorHandler ? (...attributes) => {
      try {
        resolve(options.onImageErrorHandler(...attributes));
      } catch (error) {
        reject(error);
      }
    } : reject;
    const image = clonedNode;
    if (image.decode) {
      image.decode = resolve;
    }
    if (image.loading === "lazy") {
      image.loading = "eager";
    }
    if (isImageElement) {
      clonedNode.srcset = "";
      clonedNode.src = dataURL;
    } else {
      clonedNode.href.baseVal = dataURL;
    }
  });
}
async function embedChildren(clonedNode, options) {
  const children = toArray(clonedNode.childNodes);
  const deferreds = children.map((child) => embedImages(child, options));
  await Promise.all(deferreds).then(() => clonedNode);
}
async function embedImages(clonedNode, options) {
  if (isInstanceOfElement(clonedNode, Element)) {
    await embedBackground(clonedNode, options);
    await embedImageNode(clonedNode, options);
    await embedChildren(clonedNode, options);
  }
}

// node_modules/html-to-image/es/apply-style.js
function applyStyle(node, options) {
  const { style } = node;
  if (options.backgroundColor) {
    style.backgroundColor = options.backgroundColor;
  }
  if (options.width) {
    style.width = `${options.width}px`;
  }
  if (options.height) {
    style.height = `${options.height}px`;
  }
  const manual = options.style;
  if (manual != null) {
    Object.keys(manual).forEach((key) => {
      style[key] = manual[key];
    });
  }
  return node;
}

// node_modules/html-to-image/es/embed-webfonts.js
var cssFetchCache = {};
async function fetchCSS(url) {
  let cache2 = cssFetchCache[url];
  if (cache2 != null) {
    return cache2;
  }
  const res = await fetch(url);
  const cssText = await res.text();
  cache2 = { url, cssText };
  cssFetchCache[url] = cache2;
  return cache2;
}
async function embedFonts(data, options) {
  let cssText = data.cssText;
  const regexUrl = /url\(["']?([^"')]+)["']?\)/g;
  const fontLocs = cssText.match(/url\([^)]+\)/g) || [];
  const loadFonts = fontLocs.map(async (loc) => {
    let url = loc.replace(regexUrl, "$1");
    if (!url.startsWith("https://")) {
      url = new URL(url, data.url).href;
    }
    return fetchAsDataURL(url, options.fetchRequestInit, ({ result }) => {
      cssText = cssText.replace(loc, `url(${result})`);
      return [loc, result];
    });
  });
  return Promise.all(loadFonts).then(() => cssText);
}
function parseCSS(source) {
  if (source == null) {
    return [];
  }
  const result = [];
  const commentsRegex = /(\/\*[\s\S]*?\*\/)/gi;
  let cssText = source.replace(commentsRegex, "");
  const keyframesRegex = new RegExp("((@.*?keyframes [\\s\\S]*?){([\\s\\S]*?}\\s*?)})", "gi");
  while (true) {
    const matches = keyframesRegex.exec(cssText);
    if (matches === null) {
      break;
    }
    result.push(matches[0]);
  }
  cssText = cssText.replace(keyframesRegex, "");
  const importRegex = /@import[\s\S]*?url\([^)]*\)[\s\S]*?;/gi;
  const combinedCSSRegex = "((\\s*?(?:\\/\\*[\\s\\S]*?\\*\\/)?\\s*?@media[\\s\\S]*?){([\\s\\S]*?)}\\s*?})|(([\\s\\S]*?){([\\s\\S]*?)})";
  const unifiedRegex = new RegExp(combinedCSSRegex, "gi");
  while (true) {
    let matches = importRegex.exec(cssText);
    if (matches === null) {
      matches = unifiedRegex.exec(cssText);
      if (matches === null) {
        break;
      } else {
        importRegex.lastIndex = unifiedRegex.lastIndex;
      }
    } else {
      unifiedRegex.lastIndex = importRegex.lastIndex;
    }
    result.push(matches[0]);
  }
  return result;
}
async function getCSSRules(styleSheets, options) {
  const ret = [];
  const deferreds = [];
  styleSheets.forEach((sheet) => {
    if ("cssRules" in sheet) {
      try {
        toArray(sheet.cssRules || []).forEach((item, index) => {
          if (item.type === CSSRule.IMPORT_RULE) {
            let importIndex = index + 1;
            const url = item.href;
            const deferred = fetchCSS(url).then((metadata) => embedFonts(metadata, options)).then((cssText) => parseCSS(cssText).forEach((rule) => {
              try {
                sheet.insertRule(rule, rule.startsWith("@import") ? importIndex += 1 : sheet.cssRules.length);
              } catch (error) {
                console.error("Error inserting rule from remote css", {
                  rule,
                  error
                });
              }
            })).catch((e) => {
              console.error("Error loading remote css", e.toString());
            });
            deferreds.push(deferred);
          }
        });
      } catch (e) {
        const inline = styleSheets.find((a) => a.href == null) || document.styleSheets[0];
        if (sheet.href != null) {
          deferreds.push(fetchCSS(sheet.href).then((metadata) => embedFonts(metadata, options)).then((cssText) => parseCSS(cssText).forEach((rule) => {
            inline.insertRule(rule, inline.cssRules.length);
          })).catch((err) => {
            console.error("Error loading remote stylesheet", err);
          }));
        }
        console.error("Error inlining remote css file", e);
      }
    }
  });
  return Promise.all(deferreds).then(() => {
    styleSheets.forEach((sheet) => {
      if ("cssRules" in sheet) {
        try {
          toArray(sheet.cssRules || []).forEach((item) => {
            ret.push(item);
          });
        } catch (e) {
          console.error(`Error while reading CSS rules from ${sheet.href}`, e);
        }
      }
    });
    return ret;
  });
}
function getWebFontRules(cssRules) {
  return cssRules.filter((rule) => rule.type === CSSRule.FONT_FACE_RULE).filter((rule) => shouldEmbed(rule.style.getPropertyValue("src")));
}
async function parseWebFontRules(node, options) {
  if (node.ownerDocument == null) {
    throw new Error("Provided element is not within a Document");
  }
  const styleSheets = toArray(node.ownerDocument.styleSheets);
  const cssRules = await getCSSRules(styleSheets, options);
  return getWebFontRules(cssRules);
}
function normalizeFontFamily(font) {
  return font.trim().replace(/["']/g, "");
}
function getUsedFonts(node) {
  const fonts = /* @__PURE__ */ new Set();
  function traverse(node2) {
    const fontFamily = node2.style.fontFamily || getComputedStyle(node2).fontFamily;
    fontFamily.split(",").forEach((font) => {
      fonts.add(normalizeFontFamily(font));
    });
    Array.from(node2.children).forEach((child) => {
      if (child instanceof HTMLElement) {
        traverse(child);
      }
    });
  }
  traverse(node);
  return fonts;
}
async function getWebFontCSS(node, options) {
  const rules = await parseWebFontRules(node, options);
  const usedFonts = getUsedFonts(node);
  const cssTexts = await Promise.all(rules.filter((rule) => usedFonts.has(normalizeFontFamily(rule.style.fontFamily))).map((rule) => {
    const baseUrl = rule.parentStyleSheet ? rule.parentStyleSheet.href : null;
    return embedResources(rule.cssText, baseUrl, options);
  }));
  return cssTexts.join("\n");
}
async function embedWebFonts(clonedNode, options) {
  const cssText = options.fontEmbedCSS != null ? options.fontEmbedCSS : options.skipFonts ? null : await getWebFontCSS(clonedNode, options);
  if (cssText) {
    const styleNode = document.createElement("style");
    const sytleContent = document.createTextNode(cssText);
    styleNode.appendChild(sytleContent);
    if (clonedNode.firstChild) {
      clonedNode.insertBefore(styleNode, clonedNode.firstChild);
    } else {
      clonedNode.appendChild(styleNode);
    }
  }
}

// node_modules/html-to-image/es/index.js
async function toSvg(node, options = {}) {
  const { width, height } = getImageSize(node, options);
  const clonedNode = await cloneNode(node, options, true);
  await embedWebFonts(clonedNode, options);
  await embedImages(clonedNode, options);
  applyStyle(clonedNode, options);
  const datauri = await nodeToDataURL(clonedNode, width, height);
  return datauri;
}
async function toCanvas(node, options = {}) {
  const { width, height } = getImageSize(node, options);
  const svg = await toSvg(node, options);
  const img = await createImage(svg);
  const canvas = document.createElement("canvas");
  const context = canvas.getContext("2d");
  const ratio = options.pixelRatio || getPixelRatio();
  const canvasWidth = options.canvasWidth || width;
  const canvasHeight = options.canvasHeight || height;
  canvas.width = canvasWidth * ratio;
  canvas.height = canvasHeight * ratio;
  if (!options.skipAutoScale) {
    checkCanvasDimensions(canvas);
  }
  canvas.style.width = `${canvasWidth}`;
  canvas.style.height = `${canvasHeight}`;
  if (options.backgroundColor) {
    context.fillStyle = options.backgroundColor;
    context.fillRect(0, 0, canvas.width, canvas.height);
  }
  context.drawImage(img, 0, 0, canvas.width, canvas.height);
  return canvas;
}
async function toPng(node, options = {}) {
  const canvas = await toCanvas(node, options);
  return canvas.toDataURL();
}

// src/themes.ts
function makeRng(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = a + 1831565813 | 0;
    let t = Math.imul(a ^ a >>> 15, 1 | a);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}
var NOISE_LIGHT = `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`;
var NOISE_DARK = `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='5' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`;
var COMPASS = (c) => `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='800' height='800' viewBox='0 0 800 800'%3E%3Cg fill='none' stroke='${c}' stroke-width='1.4' stroke-linecap='round' stroke-linejoin='round'%3E%3Ccircle cx='400' cy='400' r='394'/%3E%3Ccircle cx='400' cy='400' r='372'/%3E%3Ccircle cx='400' cy='400' r='336' stroke-dasharray='2 16'/%3E%3Ccircle cx='400' cy='400' r='300'/%3E%3Ccircle cx='400' cy='400' r='150'/%3E%3Cline x1='700' y1='400' x2='772' y2='400'/%3E%3Cline x1='612' y1='612' x2='663' y2='663'/%3E%3Cline x1='400' y1='700' x2='400' y2='772'/%3E%3Cline x1='188' y1='612' x2='137' y2='663'/%3E%3Cline x1='100' y1='400' x2='28' y2='400'/%3E%3Cline x1='188' y1='188' x2='137' y2='137'/%3E%3Cline x1='400' y1='100' x2='400' y2='28'/%3E%3Cline x1='612' y1='188' x2='663' y2='137'/%3E%3Cpolyline points='250,330 250,430 330,480 410,440 250,330'/%3E%3Cpolyline points='410,440 490,470 555,530 610,560'/%3E%3C/g%3E%3Cg fill='${c}' stroke='none'%3E%3Ccircle cx='250' cy='330' r='7'/%3E%3Ccircle cx='250' cy='430' r='7'/%3E%3Ccircle cx='330' cy='480' r='7'/%3E%3Ccircle cx='410' cy='440' r='7'/%3E%3Ccircle cx='490' cy='470' r='7'/%3E%3Ccircle cx='555' cy='530' r='7'/%3E%3Ccircle cx='610' cy='560' r='7'/%3E%3C/g%3E%3C/svg%3E")`;
var PATTERN_CREAM = COMPASS("%23b9a06a");
var PATTERN_GOLD = COMPASS("%23c8a45a");
var SHARE_THEMES = [
  {
    id: "cream",
    name: "\u7C73\u767D",
    bg: "radial-gradient(1100px 820px at 50% -12%, rgba(255,255,255,0.55), transparent 55%),radial-gradient(900px 700px at 86% 112%, rgba(196,176,140,0.16), transparent 55%),linear-gradient(160deg, #f6f0e3 0%, #efe7d6 55%, #e8dec9 100%)",
    bgNoise: NOISE_LIGHT,
    pattern: PATTERN_CREAM,
    ink: "#463d31",
    dim: "#8a7f6b",
    faint: "#b3a892",
    foil: "linear-gradient(180deg, #c2a063 0%, #a3854a 52%, #8c6f37 100%)",
    line: "rgba(150,128,90,0.30)",
    ringBg: "rgba(150,128,90,0.14)",
    ringFg: "url(#scRing)",
    ringStops: ["#c2a063", "#8c6f37"],
    sealBg: "#b08a3c",
    sealInk: "#f6f0e3",
    glow: "rgba(210,186,144,0.20)"
  },
  {
    id: "black-gold",
    name: "\u9ED1\u91D1",
    dark: true,
    bg: "radial-gradient(1100px 820px at 50% -8%, rgba(222,186,110,0.10), transparent 55%),radial-gradient(900px 700px at 82% 112%, rgba(150,116,54,0.18), transparent 55%),linear-gradient(160deg, #1c1a15 0%, #131210 55%, #0b0a08 100%)",
    bgNoise: NOISE_DARK,
    pattern: PATTERN_GOLD,
    ink: "#f1e9d7",
    dim: "#b3a584",
    faint: "#6c6450",
    foil: "linear-gradient(180deg, #e7cf90 0%, #c8a45a 52%, #a9853c 100%)",
    line: "rgba(200,165,95,0.34)",
    ringBg: "rgba(200,165,95,0.16)",
    ringFg: "url(#scRing)",
    ringStops: ["#e7cf90", "#a9853c"],
    sealBg: "#b08a3c",
    sealInk: "#16140f",
    glow: "rgba(206,168,92,0.20)"
  }
];
function getTheme(id) {
  return SHARE_THEMES.find((t) => t.id === id) ?? SHARE_THEMES[0];
}
var MILESTONE_TYPES = [
  { id: "achievement", cn: "\u6210\u5C31", en: "ACHIEVEMENT", glyph: "\u2726" },
  { id: "decision", cn: "\u51B3\u7B56", en: "DECISION", glyph: "\u2726" }
];
function getMilestoneType(id) {
  return MILESTONE_TYPES.find((t) => t.id === id) ?? MILESTONE_TYPES[0];
}
var QUOTE_POOL = [
  "\u6BCF\u4E00\u6B21\u5361\u4F4F\uFF0C\u90FD\u662F\u7406\u89E3\u5728\u6572\u95E8\u3002",
  "\u60F3\u901A\u7684\u90A3\u4E00\u523B\uFF0C\u80DC\u8FC7\u4E00\u767E\u5929\u7684\u5047\u88C5\u52AA\u529B\u3002",
  "\u771F\u6B63\u7684\u8FDB\u5EA6\uFF0C\u7531\u8BA4\u77E5\u800C\u975E\u65E5\u5386\u4E08\u91CF\u3002",
  "\u4E0D\u6C42\u65E5\u65E5\u5728\u573A\uFF0C\u4F46\u6C42\u6B65\u6B65\u4E3A\u8425\u3002",
  "\u628A\u96BE\u9898\u5543\u788E\uFF0C\u624D\u662F\u901A\u5F80\u5185\u6838\u7684\u8DEF\u3002",
  "\u4EE3\u7801\u4E0D\u4F1A\u8BF4\u8C0E\uFF0C\u8DD1\u901A\u5373\u771F\u7406\u3002",
  "\u6240\u8C13\u6210\u957F\uFF0C\u662F\u628A\u300C\u4E0D\u61C2\u300D\u4E00\u4E2A\u4E2A\u53D8\u6210\u300C\u539F\u6765\u5982\u6B64\u300D\u3002",
  "\u8BFB\u8584\u4E00\u672C\u4E66\uFF0C\u80DC\u8FC7\u7FFB\u70C2\u5341\u672C\u3002",
  "Debug \u5230\u6DF1\u5904\uFF0C\u65B9\u89C1\u7CFB\u7EDF\u771F\u5BB9\u3002",
  "\u5341\u5E74\u4E00\u7EAA\uFF0C\u529F\u4E0D\u5510\u6350\u3002",
  "\u5C81\u661F\u4E1C\u884C\uFF0C\u4E00\u6B65\u4E00\u661F\u5149\u3002",
  "\u6162\u4E00\u70B9\uFF0C\u4F46\u6BCF\u4E00\u6B65\u90FD\u7B97\u6570\u3002",
  "\u5C71\u9AD8\u8DEF\u8FDC\uFF0C\u884C\u5219\u5C06\u81F3\u3002",
  "\u4E0D\u75BE\u4E0D\u5F90\uFF0C\u81EA\u6709\u5C71\u6CB3\u3002"
];
var TERM_OFFSET_MIN = [
  0,
  21208,
  42467,
  63836,
  85337,
  107014,
  128867,
  150921,
  173149,
  195551,
  218072,
  240693,
  263343,
  285989,
  308563,
  331033,
  353350,
  375494,
  397447,
  419210,
  440795,
  462224,
  483532,
  504758
];
var SOLAR_TERMS = [
  "\u5C0F\u5BD2 \xB7 \u6885\u4FE1\u521D\u4F20 \xB7 \u9759\u5F85\u6625\u5F52",
  "\u5927\u5BD2 \xB7 \u5C81\u672B\u5C06\u5C3D \xB7 \u84C4\u52BF\u5F85\u53D1",
  "\u7ACB\u6625 \xB7 \u5C81\u661F\u4E1C\u884C \xB7 \u4E07\u7269\u59CB\u751F",
  "\u96E8\u6C34 \xB7 \u597D\u96E8\u77E5\u65F6 \xB7 \u6DA6\u7269\u65E0\u58F0",
  "\u60CA\u86F0 \xB7 \u59CB\u96F7\u4E4D\u52A8 \xB7 \u4E07\u7269\u82CF\u9192",
  "\u6625\u5206 \xB7 \u663C\u591C\u5747\u957F \xB7 \u6696\u610F\u521D\u76C8",
  "\u6E05\u660E \xB7 \u98CE\u81F3\u5929\u6E05 \xB7 \u8349\u6728\u840C\u53D1",
  "\u8C37\u96E8 \xB7 \u96E8\u6DA6\u767E\u8C37 \xB7 \u6ECB\u957F\u65E0\u58F0",
  "\u7ACB\u590F \xB7 \u69D0\u836B\u521D\u5BC6 \xB7 \u4E07\u7269\u5E76\u79C0",
  "\u5C0F\u6EE1 \xB7 \u672A\u6EE1\u5373\u662F \xB7 \u5C0F\u5F97\u76C8\u6EE1",
  "\u8292\u79CD \xB7 \u65F6\u96E8\u53CA\u8292 \xB7 \u5FD9\u4E8E\u7A51\u4E8B",
  "\u590F\u81F3 \xB7 \u65E5\u6C38\u9633\u6781 \xB7 \u591C\u77ED\u663C\u957F",
  "\u5C0F\u6691 \xB7 \u6E29\u98CE\u59CB\u81F3 \xB7 \u5FC3\u9759\u81EA\u51C9",
  "\u5927\u6691 \xB7 \u6691\u6C14\u65B9\u9000 \xB7 \u5FC3\u9759\u81EA\u7136",
  "\u7ACB\u79CB \xB7 \u79BE\u8C37\u5F85\u719F \xB7 \u51C9\u98CE\u6E10\u8D77",
  "\u5904\u6691 \xB7 \u6691\u6C14\u6E10\u6D88 \xB7 \u79CB\u610F\u521D\u751F",
  "\u767D\u9732 \xB7 \u6708\u76F8\u6E10\u76C8 \xB7 \u9732\u767D\u9636\u6E05",
  "\u79CB\u5206 \xB7 \u4E39\u6842\u98D8\u9999 \xB7 \u663C\u591C\u518D\u5747",
  "\u5BD2\u9732 \xB7 \u9732\u51DD\u4E3A\u767D \xB7 \u83CA\u6709\u9EC4\u534E",
  "\u971C\u964D \xB7 \u971C\u672A\u5168\u964D \xB7 \u79CB\u8272\u5C3D\u67D3",
  "\u7ACB\u51AC \xB7 \u521D\u5BD2\u4E4D\u4E34 \xB7 \u4E07\u7269\u6536\u85CF",
  "\u5C0F\u96EA \xB7 \u8F7B\u76C8\u521D\u843D \xB7 \u5929\u5730\u6E05\u5BC2",
  "\u5927\u96EA \xB7 \u96EA\u8986\u5343\u5C71 \xB7 \u56F4\u7089\u5411\u6696",
  "\u51AC\u81F3 \xB7 \u4E00\u9633\u6765\u590D \xB7 \u661F\u6CB3\u4F4E\u5782"
];
var TERM_BASE_UTC = Date.UTC(1900, 0, 6, 2, 5);
var TROPICAL_YEAR_MS = 315569259747e-1;
function termBeijingDate(year, n) {
  const ms = TERM_BASE_UTC + TROPICAL_YEAR_MS * (year - 1900) + TERM_OFFSET_MIN[n] * 6e4;
  return new Date(ms + 8 * 3600 * 1e3);
}
function pick(rng, arr) {
  return arr[Math.floor(rng() * arr.length) % arr.length];
}
function pickQuote(rng) {
  return pick(rng, QUOTE_POOL);
}
function getImageryByDate(date) {
  const year = date.getFullYear();
  const today = (date.getMonth() + 1) * 100 + date.getDate();
  let chosen = SOLAR_TERMS[SOLAR_TERMS.length - 1];
  for (let i = 0; i < SOLAR_TERMS.length; i++) {
    const bj = termBeijingDate(year, i);
    const md = (bj.getUTCMonth() + 1) * 100 + bj.getUTCDate();
    if (today >= md) chosen = SOLAR_TERMS[i];
    else break;
  }
  return chosen;
}
function pickTheme(seed) {
  return SHARE_THEMES[seed % SHARE_THEMES.length];
}
var SHARE_RATIOS = [
  { id: "wechat", label: "\u670B\u53CB\u5708", ratio: "1:1", w: 1080, h: 1080 },
  { id: "weibo", label: "\u5FAE\u535A", ratio: "9:16", w: 1080, h: 1920 },
  { id: "xhs", label: "\u5C0F\u7EA2\u4E66", ratio: "3:4", w: 1080, h: 1440 }
];

// src/card.ts
var WEEKDAYS = ["\u661F\u671F\u65E5", "\u661F\u671F\u4E00", "\u661F\u671F\u4E8C", "\u661F\u671F\u4E09", "\u661F\u671F\u56DB", "\u661F\u671F\u4E94", "\u661F\u671F\u516D"];
function pad(n) {
  return n < 10 ? "0" + n : "" + n;
}
function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}
function buildCardHTML(opts) {
  const { type, title, subtitle, seq, theme, ratio, seed } = opts;
  const t = theme;
  const now = /* @__PURE__ */ new Date();
  const todayStr = `${now.getFullYear()}.${pad(now.getMonth() + 1)}.${pad(now.getDate())}`;
  const weekday = WEEKDAYS[now.getDay()];
  const k = ratio.h / 1080;
  const rng = makeRng(seed);
  const quote = pickQuote(rng);
  const imagery = getImageryByDate(now);
  const glowX = 8 + rng() * 40;
  const glowY = 55 + rng() * 35;
  const titleText = (title || "").trim() || "\uFF08\u5199\u4E0B\u8FD9\u6B21\u91CC\u7A0B\u7891\uFF09";
  const titleLen = [...titleText].length;
  const baseTitle = titleLen <= 8 ? 92 : titleLen <= 14 ? 74 : titleLen <= 22 ? 58 : 46;
  const TITLE_SCALE = { wechat: 1, xhs: 0.98, weibo: 0.92 };
  const titleSize = baseTitle * k * (TITLE_SCALE[ratio.id] ?? 1);
  const wrap = document.createElement("div");
  wrap.className = "share-card";
  wrap.innerHTML = `
  <div class="sc-pattern-overlay"></div>
  <div class="sc-grain"></div>
  <div class="sc-glow-center" style="background: radial-gradient(circle, ${t.glow}, transparent 62%)"></div>
  <div class="sc-glow-edge" style="left:${glowX}%; top:${glowY}%; background: radial-gradient(circle, ${t.glow}, transparent 60%)"></div>

  <div class="sc-content">
    <header class="sc-head">
      <div class="sc-brand">\u5C81\u661F\u53F0<small>CIRAST</small></div>
      <div class="sc-anchor">
        <span class="sc-anchor-cn">\u5C81\u661F\u7EAA \xB7 \u7B2C ${seq} \u5EA7\u91CC\u7A0B\u7891</span>
        <span class="sc-anchor-en">MILESTONE NO.${pad(seq)}</span>
      </div>
    </header>

    <div class="sc-focus-ms">
      <div class="sc-ms-type">
        <span class="sc-ms-glyph">${type.glyph}</span>${type.cn}<em>${type.en}</em>
      </div>
      <div class="sc-ms-title">${escapeHtml(titleText)}</div>
      ${subtitle ? `<div class="sc-ms-sub">${escapeHtml(subtitle)}</div>` : ""}
      <div class="sc-ms-rule"></div>
    </div>

    <footer class="sc-foot">
      <div class="sc-quote-col">
        <div class="sc-quote">\u300C${quote}\u300D</div>
        <div class="sc-imagery">${imagery}</div>
      </div>
      <div class="sc-foot-right">
        <div class="sc-date">
          <b>${todayStr}</b>
          <span class="sc-date-cn">${weekday}</span>
          <span class="sc-date-en">${now.getFullYear()} \xB7 ${pad(now.getMonth() + 1)} \xB7 ${pad(now.getDate())}</span>
        </div>
        <div class="sc-seal">
          <span>\u5C81\u661F</span>
          <em>\u91CC\u7A0B</em>
        </div>
      </div>
    </footer>
  </div>`;
  wrap.style.width = `${ratio.w}px`;
  wrap.style.height = `${ratio.h}px`;
  wrap.style.setProperty("--sc-k", String(k));
  wrap.style.setProperty("--sc-title", `${titleSize}px`);
  wrap.style.setProperty("--sc-bg", t.bg);
  wrap.style.setProperty("--sc-bg-noise", t.bgNoise);
  wrap.style.setProperty("--sc-pattern", t.pattern);
  wrap.style.setProperty("--sc-ink", t.ink);
  wrap.style.setProperty("--sc-dim", t.dim);
  wrap.style.setProperty("--sc-faint", t.faint);
  wrap.style.setProperty("--sc-foil", t.foil);
  wrap.style.setProperty("--sc-line", t.line);
  wrap.style.setProperty("--sc-seal-bg", t.sealBg);
  wrap.style.setProperty("--sc-seal-ink", t.sealInk);
  wrap.style.setProperty("--sc-glow", t.glow);
  return wrap.outerHTML;
}

// src/milestones.ts
function countMilestones(app, milestoneFolder) {
  const folder = milestoneFolder.replace(/\/+$/, "");
  const files = app.vault.getMarkdownFiles().filter((f) => f.path === folder || f.path.startsWith(folder + "/"));
  return files.filter((f) => !/(^|\/)index\.md$/i.test(f.path)).length;
}

// src/shareModal.ts
var ShareModal = class extends import_obsidian.Modal {
  constructor(app, settings) {
    super(app);
    this.ratioIndex = 0;
    this.seed = Math.floor(Math.random() * 1e9);
    this.themeId = null;
    this.typeId = MILESTONE_TYPES[0].id;
    this.title = "";
    this.subtitle = "";
    this.seq = 1;
    this.ratioBtns = [];
    this.themeBtns = [];
    this.typeBtns = [];
    this.settings = settings;
  }
  onOpen() {
    const { contentEl, modalEl } = this;
    modalEl.style.width = "600px";
    const count = countMilestones(this.app, this.settings.milestoneFolder);
    this.seq = count + 1;
    contentEl.empty();
    contentEl.classList.add("sx-modal");
    const head = contentEl.createDiv({ cls: "sx-modal-head" });
    head.createDiv({ cls: "sx-modal-title", text: "\u751F\u6210\u91CC\u7A0B\u7891 \xB7 \u8109\u51B2\u5361" });
    const close = head.createDiv({ cls: "sx-modal-close", text: "\xD7" });
    close.onClickEvent(() => this.close());
    const body = contentEl.createDiv({ cls: "sx-modal-body" });
    const typeField = body.createDiv({ cls: "sx-field" });
    typeField.createEl("label", { cls: "sx-label", text: "\u91CC\u7A0B\u7891\u7C7B\u578B" });
    const typeRow = typeField.createDiv({ cls: "sx-type-row" });
    MILESTONE_TYPES.forEach((mt) => {
      const b = typeRow.createDiv({ cls: "sx-type-btn" });
      b.createDiv({ cls: "t-cn", text: mt.cn });
      b.createDiv({ cls: "t-en", text: mt.en });
      b.onClickEvent(() => {
        this.typeId = mt.id;
        this.render();
      });
      this.typeBtns.push(b);
    });
    const titleField = body.createDiv({ cls: "sx-field" });
    titleField.createEl("label", { cls: "sx-label", text: "\u91CC\u7A0B\u7891\u6807\u9898\uFF08\u89C6\u89C9\u91CD\u5FC3\uFF09" });
    const titleInput = titleField.createEl("input", { cls: "sx-input" });
    titleInput.type = "text";
    titleInput.placeholder = "\u4F8B\uFF1Axv6 \u9875\u8868\u6620\u5C04\u7EC8\u4E8E\u8DD1\u901A";
    titleInput.oninput = () => {
      this.title = titleInput.value;
      this.render();
    };
    const subField = body.createDiv({ cls: "sx-field" });
    subField.createEl("label", { cls: "sx-label", text: "\u4E00\u53E5\u8BDD\u6CE8\u89E3\uFF08\u53EF\u7A7A\uFF09" });
    const subInput = subField.createEl("input", { cls: "sx-input" });
    subInput.type = "text";
    subInput.placeholder = "\u4F8B\uFF1A\u5361\u4E86\u4E09\u5929\uFF0C\u539F\u6765\u662F satp \u6CA1\u5237\u65B0 TLB";
    subInput.oninput = () => {
      this.subtitle = subInput.value;
      this.render();
    };
    const seqField = body.createDiv({ cls: "sx-field" });
    seqField.createEl("label", { cls: "sx-label", text: "\u7B2C N \u5EA7\u91CC\u7A0B\u7891" });
    const seqRow = seqField.createDiv({ cls: "sx-seq-row" });
    const seqInput = seqRow.createEl("input", { cls: "sx-input" });
    seqInput.type = "number";
    seqInput.min = "1";
    seqInput.value = String(this.seq);
    seqInput.oninput = () => {
      const v = parseInt(seqInput.value, 10);
      this.seq = Number.isFinite(v) && v > 0 ? v : 1;
      this.render();
    };
    seqRow.createDiv({
      cls: "sx-seq-hint",
      text: `\u5DF2\u4F9D\u636E ${this.settings.milestoneFolder} \u81EA\u52A8\u63A8\u7B97\uFF0C\u53EF\u624B\u52A8\u8C03\u6574`
    });
    const ratioRow = body.createDiv({ cls: "sx-ratio-row" });
    SHARE_RATIOS.forEach((r, i) => {
      const b = ratioRow.createDiv({ cls: "sx-ratio-btn" });
      b.createDiv({ cls: "r-label", text: r.label });
      b.createDiv({ cls: "r-ratio", text: r.ratio });
      b.onClickEvent(() => {
        this.ratioIndex = i;
        this.render();
      });
      this.ratioBtns.push(b);
    });
    const themeRow = body.createDiv({ cls: "sx-theme-row" });
    SHARE_THEMES.forEach((th) => {
      const b = themeRow.createDiv({ cls: "sx-theme-btn" });
      const sw = b.createEl("span", { cls: "sx-theme-swatch" });
      sw.style.background = th.id === "black-gold" ? "#15130f" : "#efe7d6";
      b.createEl("span", { cls: "sx-theme-name", text: th.name });
      b.onClickEvent(() => {
        this.themeId = th.id;
        this.render();
      });
      this.themeBtns.push(b);
    });
    const dice = themeRow.createDiv({ cls: "sx-theme-btn sx-theme-dice", text: "\u{1F3B2} \u968F\u673A" });
    dice.onClickEvent(() => {
      this.themeId = null;
      this.seed = Math.floor(Math.random() * 1e9);
      this.render();
    });
    const previewWrap = body.createDiv({ cls: "sx-preview-wrap" });
    this.previewInner = previewWrap.createDiv({ cls: "sx-preview-inner" });
    this.copyBtn = body.createEl("button", { cls: "sx-copy-btn" });
    this.copyBtn.onClickEvent(() => this.copy());
    this.saveBtn = body.createEl("button", { cls: "sx-save-btn", text: "\u4FDD\u5B58\u5230\u5E93" });
    this.saveBtn.onClickEvent(() => this.save());
    this.render();
  }
  currentRatio() {
    return SHARE_RATIOS[this.ratioIndex];
  }
  currentTheme() {
    return this.themeId ? getTheme(this.themeId) : pickTheme(this.seed);
  }
  render() {
    const ratio = this.currentRatio();
    const theme = this.currentTheme();
    const type = getMilestoneType(this.typeId);
    this.previewInner.innerHTML = buildCardHTML({
      type,
      title: this.title,
      subtitle: this.subtitle,
      seq: this.seq,
      theme,
      ratio,
      seed: this.seed
    });
    const scale = Math.min(1, 420 / ratio.w);
    this.previewInner.style.width = `${ratio.w * scale}px`;
    this.previewInner.style.height = `${ratio.h * scale}px`;
    this.previewInner.style.transform = `scale(${scale})`;
    this.previewInner.style.transformOrigin = "top left";
    this.copyBtn.textContent = `\u{1F4CB} \u4E00\u952E\u590D\u5236\uFF08${ratio.label} ${ratio.ratio} \xB7 ${theme.name}\uFF09`;
    this.ratioBtns.forEach((b, i) => b.toggleClass("active", i === this.ratioIndex));
    this.typeBtns.forEach((b, i) => b.toggleClass("active", MILESTONE_TYPES[i].id === this.typeId));
    this.themeBtns.forEach(
      (b, i) => b.toggleClass("active", !this.themeId && i === SHARE_THEMES.indexOf(pickTheme(this.seed)))
    );
    if (this.themeId) {
      this.themeBtns.forEach((b, i) => b.toggleClass("active", SHARE_THEMES[i].id === this.themeId));
    }
  }
  cardEl() {
    return this.previewInner.querySelector(".share-card");
  }
  async snapshot() {
    const el = this.cardEl();
    if (!el) return null;
    const ratio = this.currentRatio();
    const theme = this.currentTheme();
    return toPng(el, {
      width: ratio.w,
      height: ratio.h,
      pixelRatio: 1,
      cacheBust: true,
      backgroundColor: theme.dark ? "#0f1113" : "#F5F5DC"
    });
  }
  async copy() {
    this.copyBtn.disabled = true;
    const old = this.copyBtn.textContent;
    this.copyBtn.textContent = "\u751F\u6210\u4E2D\u2026";
    try {
      const dataUrl = await this.snapshot();
      if (!dataUrl) throw new Error("\u672A\u627E\u5230\u5206\u4EAB\u5361\u5143\u7D20");
      const blob = await (await fetch(dataUrl)).blob();
      await navigator.clipboard.write([new ClipboardItem({ "image/png": blob })]);
      new import_obsidian.Notice("\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F\uFF0C\u53BB\u5206\u4EAB\u5427 \u2728");
    } catch (e) {
      console.error("[cirast-checkin] copy failed", e);
      new import_obsidian.Notice("\u590D\u5236\u5931\u8D25\uFF1A" + (e instanceof Error ? e.message : "\u672A\u77E5\u9519\u8BEF"));
    } finally {
      this.copyBtn.disabled = false;
      this.copyBtn.textContent = old;
    }
  }
  async save() {
    this.saveBtn.disabled = true;
    const old = this.saveBtn.textContent;
    this.saveBtn.textContent = "\u5BFC\u51FA\u4E2D\u2026";
    try {
      const dataUrl = await this.snapshot();
      if (!dataUrl) throw new Error("\u672A\u627E\u5230\u5206\u4EAB\u5361\u5143\u7D20");
      const base64 = dataUrl.split(",")[1];
      const bin = Uint8Array.from(atob(base64), (c) => c.charCodeAt(0));
      const ab = bin.buffer.slice(bin.byteOffset, bin.byteOffset + bin.byteLength);
      const base = this.settings.exportFolder.replace(/\/+$/, "");
      if (!this.app.vault.getAbstractFileByPath(base)) {
        try {
          await this.app.vault.createFolder(base);
        } catch {
        }
      }
      const n = /* @__PURE__ */ new Date();
      const stamp = `${n.getFullYear()}-${String(n.getMonth() + 1).padStart(2, "0")}-${String(n.getDate()).padStart(2, "0")}`;
      const path = `${base}/${stamp}-milestone-${this.seq}.png`;
      await this.app.vault.createBinary(path, ab);
      new import_obsidian.Notice(`\u5DF2\u4FDD\u5B58\u5230 ${path}`);
    } catch (e) {
      console.error("[cirast-checkin] save failed", e);
      new import_obsidian.Notice("\u4FDD\u5B58\u5931\u8D25\uFF1A" + (e instanceof Error ? e.message : "\u672A\u77E5\u9519\u8BEF"));
    } finally {
      this.saveBtn.disabled = false;
      this.saveBtn.textContent = old;
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  milestoneFolder: "content/04-\u5C81\u661F\u7EAA",
  exportFolder: "attachments/pulses"
};

// src/main.ts
var CirastCheckinPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("milestone", "\u5C81\u661F\u53F0 \xB7 \u91CC\u7A0B\u7891\u8109\u51B2", () => this.openShare());
    this.addCommand({
      id: "share-milestone",
      name: "\u751F\u6210\u91CC\u7A0B\u7891\u8109\u51B2\u5361",
      callback: () => this.openShare()
    });
    this.addSettingTab(new CirastSettingTab(this));
  }
  onunload() {
  }
  openShare() {
    new ShareModal(this.app, this.settings).open();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var CirastSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(plugin) {
    super(plugin.app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u5C81\u661F\u53F0 \xB7 \u91CC\u7A0B\u7891\u8109\u51B2" });
    new import_obsidian2.Setting(containerEl).setName("\u91CC\u7A0B\u7891\u76EE\u5F55").setDesc(
      "vault \u5185\u76F8\u5BF9\u8DEF\u5F84\u3002\u7D2F\u8BA1\u91CC\u7A0B\u7891\u6570 = \u8BE5\u76EE\u5F55\u4E0B\u7684\u7B14\u8BB0\u6570\uFF08\u6392\u9664 index\uFF09\uFF0C\u53EA\u5728\u4F60\u771F\u6B63\u8FBE\u6210\u65F6\u589E\u957F\uFF08\u9ED8\u8BA4 content/04-\u5C81\u661F\u7EAA\uFF09\u3002"
    ).addText(
      (text) => text.setPlaceholder("content/04-\u5C81\u661F\u7EAA").setValue(this.plugin.settings.milestoneFolder).onChange(async (value) => {
        this.plugin.settings.milestoneFolder = value.trim() || "content/04-\u5C81\u661F\u7EAA";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5BFC\u51FA\u76EE\u5F55").setDesc("\u70B9\u51FB\u300C\u4FDD\u5B58\u5230\u5E93\u300D\u65F6\uFF0C\u91CC\u7A0B\u7891\u56FE\u5199\u5165\u8BE5\u76EE\u5F55\uFF08\u9ED8\u8BA4 attachments/pulses\uFF0C\u4E3A\u79C1\u6709\u672C\u5730\u76EE\u5F55\uFF0C\u4E0D\u53D1\u5E03\uFF09\u3002").addText(
      (text) => text.setPlaceholder("attachments/pulses").setValue(this.plugin.settings.exportFolder).onChange(async (value) => {
        this.plugin.settings.exportFolder = value.trim() || "attachments/pulses";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5173\u4E8E").setDesc(
      "\u544A\u522B\u6BCF\u65E5\u6253\u5361\u3002\u8FD9\u91CC\u4EE5\u300C\u8109\u51B2\u300D\u4E3A\u5355\u4F4D\u8BB0\u5F55\u6210\u679C\u2014\u2014\u53EA\u6709\u6210\u5C31 / \u51B3\u7B56\u65F6\u624D\u751F\u6210\u4E00\u5F20\u91CC\u7A0B\u7891\u5361\u3002\u8282\u594F\u7531\u8BA4\u77E5\u51B3\u5B9A\uFF0C\u4E0D\u7531\u65E5\u5386\u51B3\u5B9A\u3002"
    );
  }
};
